import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Slip 18 - Question 1
 * Program: Servlet that displays the current system date and time.
 * Concepts: Servlet, HttpServlet, doGet(), Date
 * Unit: UNIT 3 – Servlets
 */
@WebServlet("/datetime")
public class DateTimeServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        response.setContentType("text/html");
        PrintWriter out = response.getWriter();

        // Get current date and time
        Date now = new Date();

        out.println("<!DOCTYPE html>");
        out.println("<html><head><title>Date & Time</title>");
        out.println("<style>");
        out.println("body{font-family:Arial,sans-serif;margin:60px;background:#e8eaf6;text-align:center}");
        out.println(".card{background:white;padding:40px;border-radius:12px;display:inline-block;");
        out.println("      box-shadow:0 4px 12px rgba(0,0,0,0.15);min-width:400px}");
        out.println("h2{color:#3f51b5;margin-bottom:10px}");
        out.println(".dt{font-size:22px;color:#333;margin:20px 0}");
        out.println(".lbl{color:#888;font-size:14px}");
        out.println("</style></head><body>");
        out.println("<div class='card'>");
        out.println("<h2>&#128197; Current Date &amp; Time</h2>");
        out.println("<div class='lbl'>Server Date &amp; Time:</div>");
        out.println("<div class='dt'>" + now + "</div>");
        out.println("<hr/>");
        out.println("<div class='lbl'>Generated by: " + this.getClass().getSimpleName() + "</div>");
        out.println("</div></body></html>");
    }
}
